id: I979FB099
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T19:28:45+00:00'
last_modified: '2022-06-09T07:40:23.285353+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG1654
  title: འཇམ་དབྱངས་མཁྱེན་བརྩེའི་དབང་པོའི་རྣམ་ཐར་བསྡུས་པ་ཨུ་དུམྦ་རའི་དགའ་ཚལ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    292E:
      image_group_id: I1KG1706
      title: Volume 1 of 'jam dbyangs mkhyen brtse'i dbang po'i rnam thar bsdus pa
        u dum+ba ra'i dga' tshal
      total_pages: 238
      order: 1
      base_file: 292E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
