id: I979FB099
legacy_id: P007932
ocr_import_info:
  bdrc_scan_id: W1KG1654
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T19:27:17'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T08:34:08.875305+00:00'
last_modified: 2022-08-31 16:34:17.535064
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG1654
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG1654
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འཇམ་དབྱངས་མཁྱེན་བརྩེའི་དབང་པོའི་རྣམ་ཐར་བསྡུས་པ་ཨུ་དུམྦ་རའི་དགའ་ཚལ།
  author: འཇམ་མགོན་ཀོང་སྤྲུལ་བློ་གྲོས་མཐའ་ཡས།
statistics:
  ocr_word_mean_confidence_index: 0.634323535906426
  ocr_word_median_confidence_index: 0.6600000262260437
quality: null
bases:
  I1KG1706:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG1706
      total_pages: 238
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG1706.txt
    statistics:
      ocr_word_median_confidence_index: 0.6600000262260437
      ocr_word_mean_confidence_index: 0.634323535906426
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
