id: P007932
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG1654
  title: འཇམ་དབྱངས་མཁྱེན་བརྩེའི་དབང་པོའི་རྣམ་ཐར་བསྡུས་པ་ཨུ་དུམྦ་རའི་དགའ་ཚལ
  author: ''
  volumes:
    31895445138f4a57bc8af6271d5074d0:
      image_group_id: I1KG1706
      title: ''
      volume_number: 1
      total_pages: 238
ebook_metadata:
  title: འཇམ་དབྱངས་མཁྱེན་བརྩེའི་དབང་པོའི་རྣམ་ཐར་བསྡུས་པ་ཨུ་དུམྦ་རའི་དགའ་ཚལ
  author: ''
  sku: P007932
  cover: cover.jpg
  layers:
  - pagination
